# Change these first
owner: upgrademedia # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Hitpiece Client (Staging)
    url: https://staging.hitpiece.com
  - name: Hitpiece Auth via Hasura Backend Plus (Staging)
    url: https://auth-staging.hitpiece.com/healthz
  - name: Hitpiece GraphQL Engine via Hasura (Staging)
    url: https://hasura-staging.hitpiece.com/healthz

status-website:
  baseUrl: /upptime
  logoUrl: https://upgrademedia-docs.netlify.app/img/logo.png
  name: UpgradeMedia
  introTitle: "**UpgradeMedia** is a white glove, high value, and high touch point software development agency"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upgrademedia/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/upgrademedia/upptime
    - title: Website
      href: https://upgrademedia.com 
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
