# Change these first
owner: upgrademedia # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Hitpiece Client (Staging)
    url: https://staging.hitpiece.com
  - name: Hitpiece Auth via Hasura Backend Plus (Staging)
    url: https://auth-staging.hitpiece.com/healthz
  - name: Hitpiece GraphQL Engine via Hasura (Staging)
    url: https://hasura-staging.hitpiece.com/healthz

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
